### ISSUE TITLE
Social links on the footer are Databiz's instead of Bitrock's

### ISSUE THREAD

**Issue by francescopellegrini** [bitrockteam/bitrock-website#7]
I couldn't figure out where `social.js`, which has the correct links, is used and why `app.js` has Databiz's ones.

**Comment by moebiusmania** [comment]
@francescopellegrini `social.js`is related to a different part of the UI that has been deprecated, refer to `app.js`for the footer links. I need to make some refactor & code cleaning 😅

**Comment by francescopellegrini** [comment]
@moebiusmania ok, thanks.

**Comment by moebiusmania** [comment]
@francescopellegrini for the incoming v1.3 release, the `src` folder has been dramatically simplified 😎(hope to have it deployed in prod on the next week)
